name = "markdowner"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat"]


browser = { binding = "MYBROWSER" }

[[kv_namespaces]]
binding= "MD_CACHE"
id = "b587d4c164f34e2e8d89a29e2c8372b7"
preview_id = "81ac09211c85406b8738a540d9c168a1"
